-- OGPチェッカーツールをデータベースに追加
INSERT INTO tools (
  id,
  slug,
  title,
  description,
  category,
  subcategory,
  tags,
  icon,
  href,
  image_url,
  is_premium,
  is_private,
  is_new,
  is_popular,
  is_active,
  likes_count,
  view_count,
  created_at,
  updated_at
) VALUES (
  gen_random_uuid(),
  'ogp-checker',
  'OGPチェッカー',
  'URLを入力するだけで、メタデータ・OGP画像・Twitter Card・Facebook Cardを瞬時にチェック。ブロガー・SEO担当者必携の無料ツール。',
  'SEO・分析',
  'メタデータ確認',
  ARRAY['OGPチェッカー', 'メタデータチェッカー', 'OGP画像確認', 'Twitter Card確認', 'Facebook Card確認', 'メタタグ確認', 'SEOチェッカー', 'OGP検証', 'メタデータ検証', 'OGP画像サイズ', 'Twitter Card検証', 'Facebook Card検証', 'Open Graph確認', 'メタタグチェッカー', 'SEOツール', 'ブロガーツール', '無料OGPチェッカー', 'オンラインOGPチェッカー', 'OGP画像最適化', 'メタデータ最適化', 'SNS最適化', 'ソーシャルメディア最適化', 'OGP画像生成', 'メタデータ生成', 'SEO分析', 'ウェブサイト分析'],
  '🔍',
  '/tools/ogp-checker',
  '/ogp/ogp-checker-tool.png',
  false,
  false,
  true,
  true,
  true,
  0,
  0,
  NOW(),
  NOW()
);
